url1="https://mozbuy.com/product-category/computadores/"
url2="https://mozbuy.com/product-category/rede-e-servidores/"
url3="https://mozbuy.com/product-category/pc-gamer/"
url4="https://mozbuy.com/product-category/Smart-Tv/"
url5="https://mozbuy.com/product-category/home-theater/"
url6="https://mozbuy.com/product-category/projetores/"
url7="https://mozbuy.com/product-category/cartuchos-e-tonners/"
url8="https://mozbuy.com/product-category/impressoras-e-multifuncionais/"
url9="https://mozbuy.com/product-category/papelaria/"
url10="https://mozbuy.com/product-category/scanners-e-leitores/"
url11="https://mozbuy.com/product-category/telefonia-acessorios/"
url12="https://mozbuy.com/product-category/smartphones/"
url13="https://mozbuy.com/product-category/smartwatch/"
url14="https://mozbuy.com/product-category/tablets/"
url15="https://mozbuy.com/product-category/cameras-digitais/"
url16="https://mozbuy.com/product-category/drones/"
url17="https://mozbuy.com/product-category/filmadoras/"
url18="https://mozbuy.com/product-category/cameras-acessorios/"
url19="https://mozbuy.com/product-category/blusas/"
url20="https://mozbuy.com/product-category/calcas-femininas/"
url21="https://mozbuy.com/product-category/moda-intima/"
url22="https://mozbuy.com/product-category/vestidos/"
url23="https://mozbuy.com/product-category/bebes/"
url24="https://mozbuy.com/product-category/infantil-blusas-e-camisetas/"
url25="https://mozbuy.com/product-category/infantil-calcas-jeans/"
url26="https://mozbuy.com/product-category/conjuntos/"
url27="https://mozbuy.com/product-category/calcado-feminino/"
url28="https://mozbuy.com/product-category/calcado-masculino/"
url29="https://mozbuy.com/product-category/calcado-infantil/"
url30="https://mozbuy.com/product-category/camisetas/"
url31="https://mozbuy.com/product-category/calca-jeans/"
url32="https://mozbuy.com/product-category/maquiagem/"
url33="https://mozbuy.com/product-category/perfumes/"
url34="https://mozbuy.com/product-category/cabelos-perucas/"
url35="https://mozbuy.com/product-category/oculos-de-sol/"
url36="https://mozbuy.com/product-category/carteiras-femininas/"
url37="https://mozbuy.com/product-category/bijuterias/"
url38="https://mozbuy.com/product-category/ternos/"
url39="https://mozbuy.com/product-category/acessorios-de-iluminacao/"
url40="https://mozbuy.com/product-category/iluminacao-exterior/"
url41="https://mozbuy.com/product-category/iluminacao-interior/"
url42="https://mozbuy.com/product-category/produtos-para-casa/"
url43="https://mozbuy.com/product-category/festas-e-eventos/"
url44="https://mozbuy.com/product-category/papel-de-parede/"
url45="https://mozbuy.com/product-category/maquina-de-lavar/"
url46="https://mozbuy.com/product-category/geleiras-fogoes/"
url47="https://mozbuy.com/product-category/banheiro-quartos/"
url48="https://mozbuy.com/product-category/sala-de-estar/"
url49="https://mozbuy.com/product-category/jardim-e-lazer/"
url50="https://mozbuy.com/product-category/cozinha/"
url51="https://mozbuy.com/product-category/material-de-campismo/"
url52="https://mozbuy.com/product-category/acessorios-desportivos/"
url53="https://mozbuy.com/product-category/desportos-aquaticos/"
url54="https://mozbuy.com/product-category/desportos-coletivos/"
url55="https://mozbuy.com/product-category/garrafas-e-squeezes/"
url56="https://mozbuy.com/product-category/vitaminas/"
url57="https://mozbuy.com/product-category/vitaminas/"
url58="https://mozbuy.com/product-category/whey-proteins/"
url59="https://mozbuy.com/product-category/equipamentos-fitness/"
url60="https://mozbuy.com/product-category/halteres-e-pesos/"
url61="https://mozbuy.com/product-category/bicicletas-estaticas/"
url62="https://mozbuy.com/product-category/passadeiras-de-corrida/"
url63="https://mozbuy.com/product-category/monociclos/"
url64="https://mozbuy.com/product-category/trotinetes/"
url65="https://mozbuy.com/product-category/bicicletas/"
url66="https://mozbuy.com/product-category/skates/"
url67="https://mozbuy.com/product-category/filmes-e-series/"
url68="https://mozbuy.com/product-category/musica/"
url69="https://mozbuy.com/product-category/livros/"
url70="https://mozbuy.com/product-category/audiobooks/"
url71="https://mozbuy.com/product-category/moveis-e-iluminacao/"
url72="https://mozbuy.com/product-category/papeis-agendas/"
url73="https://mozbuy.com/product-category/materiais-de-escrita/"
url74="https://mozbuy.com/product-category/acessorios-musicais/"
url75="https://mozbuy.com/product-category/instrumentos-tradicionais/"
url76="https://mozbuy.com/product-category/teclados-musicais/"
url77="https://mozbuy.com/product-category/guitarras-e-baixos/"
url78="https://mozbuy.com/product-category/telefones-ip-e-speakers/"
url79="https://mozbuy.com/product-category/impressoras/"
url80="https://mozbuy.com/product-category/plastificadoras/"
url81="https://mozbuy.com/product-category/destruidoras-de-papel/"
url82="https://mozbuy.com/product-category/mais-mobiliario/"
url83="https://mozbuy.com/product-category/mesas-de-trabalho/"
url84="https://mozbuy.com/product-category/cadeiras/"
url85="https://mozbuy.com/product-category/maquinas-eletricas/"
url86="https://mozbuy.com/product-category/pecas-p-automoveis/"
url87="https://mozbuy.com/product-category/acessorios-para-exterior/"
url88="https://mozbuy.com/product-category/acessorios-para-interior/"
url89="https://mozbuy.com/product-category/motos/"
url90="https://mozbuy.com/product-category/autocarros/"
url91="https://mozbuy.com/product-category/camioes/"
url92="https://mozbuy.com/product-category/barcos/"
url93="https://mozbuy.com/product-category/carros/"
url94="https://mozbuy.com/product-category/ferramentas-para-construcao/"
url95="https://mozbuy.com/product-category/ferramentas-eletricas/"
url96="https://mozbuy.com/product-category/ferramentas-automotivas/"
url97="https://mozbuy.com/product-category/ferramentas-acessorios/"
url98="https://mozbuy.com/product-category/fabricacao-de-equipamentos-eletricos/"
url99="https://mozbuy.com/product-category/materiais-de-construcao/"
url100="https://mozbuy.com/product-category/embalagem-e-impressao/"
url101="https://mozbuy.com/product-category/equipamentos-de-agricultura/"
url102="https://mozbuy.com/product-category/equipamentos-de-limpeza/"
url103="https://mozbuy.com/product-category/gamepad/"
url104="https://mozbuy.com/product-category/smartphones/"
url105="https://mozbuy.com/product-category/speaker/"


mozbuyurls = [
url1,
url2,
url3,
url4,
url5,
url6,
url7,
url8,
url9,
url10,
url11,
url12,
url13,
url14,
url15,
url16,
url17,
url18,
url19,
url20,
url21,
url22,
url23,
url24,
url25,
url26,
url27,
url28,
url29,
url30,
url31,
url32,
url33,
url34,
url35,
url36,
url37,
url38,
url39,
url40,
url41,
url42,
url43,
url44,
url45,
url46,
url47,
url48,
url49,
url50,
url51,
url52,
url53,
url54,
url55,
url56,
url57,
url58,
url59,
url60,
url61,
url62,
url63,
url64,
url65,
url66,
url67,
url68,
url69,
url70,
url71,
url72,
url73,
url74,
url75,
url76,
url77,
url78,
url79,
url80,
url81,
url82,
url83,
url84,
url85,
url86,
url87,
url88,
url89,
url90,
url91,
url92,
url93,
url94,
url95,
url96,
url97,
url98,
url99,
url100,
url101,
url102,
url103,
url104,
url105,
]

mozbuynames = [
'url1',
'url2',
'url3',
'url4',
'url5',
'url6',
'url7',
'url8',
'url9',
'url10',
'url11',
'url12',
'url13',
'url14',
'url15',
'url16',
'url17',
'url18',
'url19',
'url20',
'url21',
'url22',
'url23',
'url24',
'url25',
'url26',
'url27',
'url28',
'url29',
'url30',
'url31',
'url32',
'url33',
'url34',
'url35',
'url36',
'url37',
'url38',
'url39',
'url40',
'url41',
'url42',
'url43',
'url44',
'url45',
'url46',
'url47',
'url48',
'url49',
'url50',
'url51',
'url52',
'url53',
'url54',
'url55',
'url56',
'url57',
'url58',
'url59',
'url60',
'url61',
'url62',
'url63',
'url64',
'url65',
'url66',
'url67',
'url68',
'url69',
'url70',
'url71',
'url72',
'url73',
'url74',
'url75',
'url76',
'url77',
'url78',
'url79',
'url80',
'url81',
'url82',
'url83',
'url84',
'url85',
'url86',
'url87',
'url88',
'url89',
'url90',
'url91',
'url92',
'url93',
'url94',
'url95',
'url96',
'url97',
'url98',
'url99',
'url100',
'url101',
'url102',
'url103',
'url104',
'url105',
]